version: '3'
services:
  nodejs-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - postgres-db
    env_file: .env 
  postgres-db:
    image: postgres:14
    env_file: .env 
    ports:
      - "5432:5432"
